import { LegalPageLayout } from "@/components/layout/LegalPageLayout";

export function PrivacyPolicyPage() {
  return (
    <LegalPageLayout>
      <h1 className="text-3xl font-bold text-primary mb-1">Privacy Policy</h1>
      <p className="text-sm text-muted-foreground mb-2">PassAI — operated by Shryn, Inc.</p>
      <p className="text-sm text-muted-foreground mb-10">Last updated: April 14, 2026</p>

      <Section title="1. Who We Are">
        <P>PassAI is an AI-powered study tool operated by Shryn, Inc. ("we," "us," "our"). Our website is located at www.passai.study.</P>
        <P>Contact: <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a></P>
      </Section>

      <Section title="2. What Information We Collect">
        <H3>Information you provide directly</H3>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li><strong>Account information:</strong> Your email address and name when you create an account.</li>
          <li><strong>Study materials:</strong> Documents you upload (PDFs, notes, slides, text) for quiz generation.</li>
          <li><strong>Quiz responses:</strong> Your answers to quizzes, including which questions you answered correctly or incorrectly.</li>
          <li><strong>Profile settings:</strong> Your curriculum type, exam board, and exam date.</li>
          <li><strong>Payment information:</strong> When you subscribe to Pass Pro, payment is processed by Stripe. We do not store your credit card number. We receive only your Stripe customer ID, subscription status, and billing period dates.</li>
        </ul>

        <H3>Information generated by your use of PassAI</H3>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li><strong>Mastery data:</strong> Your per-topic knowledge mastery scores, calculated using Bayesian Knowledge Tracing (BKT).</li>
          <li><strong>Pass probability:</strong> Your estimated probability of passing your exam, derived from your mastery data.</li>
          <li><strong>Study plans:</strong> AI-generated study plans based on your mastery data and exam date.</li>
        </ul>

        <H3>Information collected automatically</H3>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li><strong>Usage data:</strong> Pages visited, features used, time spent, and actions taken within the app.</li>
          <li><strong>Device information:</strong> Browser type, operating system, screen resolution, and language preference.</li>
          <li><strong>Log data:</strong> IP address, access times, and referring URLs.</li>
          <li><strong>Cookies:</strong> See our Cookie Policy for details.</li>
        </ul>
      </Section>

      <Section title="3. How We Use Your Information">
        <P>We use your information to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm mb-4">
          <li>Provide and operate PassAI (generate quizzes, calculate mastery, create study plans).</li>
          <li>Process your subscription and manage your account.</li>
          <li>Send you service-related communications (account verification, subscription confirmations, important updates).</li>
          <li>Improve PassAI based on how users interact with the product.</li>
          <li>Detect and prevent fraud, abuse, or security issues.</li>
        </ul>
        <P>We do <strong>not</strong> use your information to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li>Sell your personal data to third parties.</li>
          <li>Display advertisements.</li>
          <li>Build advertising profiles.</li>
        </ul>
      </Section>

      <Section title="4. How We Share Your Information">
        <P>We share your information only with service providers that help us operate PassAI:</P>
        <table className="w-full text-sm border-collapse mb-4">
          <thead>
            <tr className="bg-secondary/40">
              <Th>Service</Th>
              <Th>Purpose</Th>
              <Th>Data shared</Th>
            </tr>
          </thead>
          <tbody>
            <tr><Td>Supabase</Td><Td>Database and authentication</Td><Td>Account data, study materials, quiz data, mastery data</Td></tr>
            <tr><Td>Anthropic (Claude API)</Td><Td>AI quiz generation and study plans</Td><Td>Text from uploaded documents (processed, not stored by Anthropic beyond the API request)</Td></tr>
            <tr><Td>Stripe</Td><Td>Payment processing</Td><Td>Email, subscription details</Td></tr>
            <tr><Td>Vercel</Td><Td>Website hosting</Td><Td>Standard web server logs</Td></tr>
            <tr><Td>Render</Td><Td>Backend API hosting</Td><Td>Standard web server logs</Td></tr>
            <tr><Td>Resend</Td><Td>Transactional email</Td><Td>Email address</Td></tr>
          </tbody>
        </table>
        <P>We may also share your information if required by law, to protect our rights, or to prevent harm.</P>
        <P>We will <strong>never</strong> sell your personal data.</P>
      </Section>

      <Section title="5. Your Uploaded Documents">
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li>Your documents are stored in our database to generate quizzes and track your learning.</li>
          <li>Document text is sent to the Anthropic Claude API to generate quiz questions. Anthropic does not retain this data beyond processing the request.</li>
          <li>Your documents are private to your account. Other users cannot see them.</li>
          <li>You can delete your documents at any time, which removes them from our database.</li>
        </ul>
      </Section>

      <Section title="6. Data Retention">
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li><strong>Account data and study materials:</strong> Retained as long as your account is active. If you delete your account, we delete your data within 30 days.</li>
          <li><strong>Payment records:</strong> Retained for 7 years as required for tax and accounting purposes.</li>
          <li><strong>Log data:</strong> Retained for up to 12 months, then deleted.</li>
        </ul>
      </Section>

      <Section title="7. Your Rights">
        <H3>All users</H3>
        <P>You have the right to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm mb-4">
          <li><strong>Access</strong> the personal data we hold about you.</li>
          <li><strong>Correct</strong> inaccurate personal data.</li>
          <li><strong>Delete</strong> your account and associated data.</li>
          <li><strong>Export</strong> your data in a machine-readable format.</li>
        </ul>
        <P>To exercise any of these rights, contact us at <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a>.</P>

        <H3>Additional rights for users in the European Economic Area (EEA) and UK</H3>
        <P>Under the GDPR, you also have the right to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm mb-4">
          <li><strong>Restrict</strong> processing of your personal data.</li>
          <li><strong>Object</strong> to processing of your personal data.</li>
          <li><strong>Data portability</strong> — receive your data in a structured, machine-readable format.</li>
          <li><strong>Withdraw consent</strong> at any time where processing is based on consent.</li>
          <li><strong>Lodge a complaint</strong> with your local data protection authority.</li>
        </ul>
        <P>Our legal basis for processing your data is:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li><strong>Performance of a contract</strong> (providing the service you signed up for).</li>
          <li><strong>Legitimate interests</strong> (improving our service, preventing fraud).</li>
          <li><strong>Consent</strong> (for non-essential cookies and marketing, if applicable).</li>
        </ul>

        <H3>Additional rights for users in California</H3>
        <P>Under the CCPA, California residents have the right to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li>Know what personal information we collect and how it is used.</li>
          <li>Request deletion of personal information.</li>
          <li>Opt out of the sale of personal information. (We do not sell personal information.)</li>
          <li>Non-discrimination for exercising your privacy rights.</li>
        </ul>
      </Section>

      <Section title="8. Age Requirements">
        <P>PassAI is intended for students aged 13 and older. We do not knowingly collect personal information from children under 13. If you are under 13, do not use PassAI. If we learn that we have collected information from a child under 13, we will delete it promptly.</P>
        <P>Users between 13 and 18 may use PassAI. By using PassAI, users between 13 and 18 confirm that they have permission from a parent or guardian to use the service.</P>
      </Section>

      <Section title="9. Cookies">
        <P>PassAI uses cookies to:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm mb-4">
          <li><strong>Keep you logged in</strong> (authentication cookies — essential, cannot be disabled).</li>
          <li><strong>Remember your preferences</strong> (essential).</li>
          <li><strong>Understand how you use PassAI</strong> (analytics cookies — optional, you can opt out).</li>
        </ul>
        <P>We do not use advertising cookies. For details on specific cookies, see our <a href="/cookies" className="text-primary hover:underline">Cookie Policy</a>.</P>

        <H3>Essential cookies</H3>
        <P>These are required for PassAI to function. They handle authentication and session management. You cannot opt out of these while using the service.</P>

        <H3>Analytics cookies</H3>
        <P>These help us understand how users interact with PassAI so we can improve the product. They are optional and disabled by default until you consent.</P>
      </Section>

      <Section title="10. Data Security">
        <P>We use industry-standard security measures to protect your data, including:</P>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-sm">
          <li>Encrypted connections (HTTPS/TLS) for all data in transit.</li>
          <li>Authentication and access controls on our database.</li>
          <li>Service provider security (Supabase, Vercel, and Render all maintain SOC 2 compliance).</li>
        </ul>
        <P className="mt-3">No system is 100% secure. If we become aware of a data breach that affects your personal information, we will notify you as required by applicable law.</P>
      </Section>

      <Section title="11. International Data Transfers">
        <P>PassAI's infrastructure is hosted in the United States. If you are located outside the United States, your data will be transferred to and processed in the United States. By using PassAI, you consent to this transfer. Where required by law (such as for EEA users), we rely on standard contractual clauses or other approved transfer mechanisms.</P>
      </Section>

      <Section title="12. Changes to This Policy">
        <P>We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or by a notice within the app. The "Last updated" date at the top of this page indicates when the policy was last revised.</P>
      </Section>

      <Section title="13. Contact Us">
        <P>If you have questions about this Privacy Policy or want to exercise your rights, contact us at:</P>
        <P><strong>Shryn, Inc.</strong><br />Email: <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a></P>
      </Section>
    </LegalPageLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border/40">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="text-base font-semibold text-foreground mt-5 mb-2">{children}</h3>;
}

function P({ children, className }: { children: React.ReactNode; className?: string }) {
  return <p className={`text-sm text-muted-foreground leading-relaxed ${className ?? ""}`}>{children}</p>;
}

function Th({ children }: { children: React.ReactNode }) {
  return <th className="text-left px-3 py-2 font-medium text-foreground border border-border/50">{children}</th>;
}

function Td({ children }: { children: React.ReactNode }) {
  return <td className="px-3 py-2 text-muted-foreground border border-border/50">{children}</td>;
}
