import { LegalPageLayout } from "@/components/layout/LegalPageLayout";

export function TermsOfServicePage() {
  return (
    <LegalPageLayout>
      <h1 className="text-3xl font-bold text-primary mb-1">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-2">PassAI — operated by Shryn, Inc.</p>
      <p className="text-sm text-muted-foreground mb-10">Last updated: April 14, 2026</p>

      <Section title="1. Agreement">
        <P>By creating an account or using PassAI ("the Service"), you agree to these Terms of Service ("Terms"). If you do not agree, do not use the Service.</P>
        <P>PassAI is operated by Shryn, Inc. ("we," "us," "our").</P>
      </Section>

      <Section title="2. Eligibility">
        <P>You must be at least 13 years old to use PassAI. By using PassAI, you confirm that you are 13 or older. If you are between 13 and 18, you confirm that you have permission from a parent or guardian to use the Service.</P>
      </Section>

      <Section title="3. Your Account">
        <P>You are responsible for maintaining the security of your account credentials. You are responsible for all activity that occurs under your account. If you believe your account has been compromised, contact us at <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a> immediately.</P>
        <P>We may suspend or terminate your account if you violate these Terms.</P>
      </Section>

      <Section title="4. What PassAI Provides">
        <P>PassAI is an AI-powered study tool that generates quizzes from your uploaded materials, tracks your knowledge mastery, estimates your probability of passing your exam, and generates study plans.</P>
        <H3>Important limitations</H3>
        <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground">
          <li><strong>PassAI does not guarantee exam results.</strong> Pass probability is an estimate based on your quiz performance, not a prediction of your actual exam outcome. Your actual results depend on many factors beyond what PassAI can measure.</li>
          <li><strong>AI-generated content may contain errors.</strong> Quiz questions, answers, and study plans are generated by AI. While we work to ensure quality, errors can occur. Always verify information with your official study materials.</li>
          <li><strong>PassAI is a supplement, not a replacement</strong> for your coursework, teachers, textbooks, or official exam preparation materials.</li>
        </ul>
      </Section>

      <Section title="5. Free and Paid Tiers">
        <H3>Starter (Free)</H3>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Upload study materials</li>
          <li>AI-generated quizzes</li>
          <li>Pass probability snapshot after each quiz</li>
          <li>1 subject</li>
        </ul>
        <H3>Pass Pro ($79/year)</H3>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Everything in Starter</li>
          <li>Unlimited subjects</li>
          <li>Knowledge Garden (topic-by-topic progress)</li>
          <li>Smart study plans</li>
          <li>Progress tracking over time</li>
        </ul>
      </Section>

      <Section title="6. Subscriptions and Billing">
        <H3>Trial</H3>
        <P>Pass Pro includes a 7-day free trial. You can cancel at any time during the trial without being charged.</P>

        <H3>Billing</H3>
        <P>Pass Pro is billed annually at $79 USD. Your subscription renews automatically unless you cancel before the renewal date.</P>

        <H3>Refund policy</H3>
        <P>You may request a full refund within 14 days of your first payment. After 14 days, no refunds are available. Refund requests must be sent to <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a>.</P>
        <P>If you cancel your subscription, you retain access to Pass Pro features until the end of your current billing period. After that, your account reverts to the Starter (free) tier. Your data is not deleted.</P>

        <H3>Price changes</H3>
        <P>We may change our pricing. If we increase the price of your current subscription, we will notify you at least 30 days in advance. The new price applies at your next renewal. If you do not agree, you may cancel before renewal.</P>
      </Section>

      <Section title="7. Your Content">
        <H3>What you upload</H3>
        <P>You retain ownership of all materials you upload to PassAI (documents, notes, text). By uploading content, you grant us a limited license to process, store, and use that content solely to provide the Service to you (generate quizzes, calculate mastery, create study plans).</P>
        <P>This license ends when you delete your content or your account.</P>

        <H3>Your responsibilities</H3>
        <P>You agree not to upload content that:</P>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>You do not have the right to use (e.g., copyrighted material you do not own or have permission to use).</li>
          <li>Contains illegal content.</li>
          <li>Contains malware or malicious code.</li>
          <li>Is designed to abuse or disrupt the Service.</li>
        </ul>
        <P className="mt-2">We do not monitor your uploads, but we reserve the right to remove content that violates these Terms.</P>

        <H3>How we use your content</H3>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Your uploaded materials are private to your account.</li>
          <li>We do not share your materials with other users.</li>
          <li>We send document text to the Anthropic Claude API for quiz generation. Anthropic does not retain this data beyond the API request.</li>
          <li>We do not use your content to train AI models.</li>
        </ul>
      </Section>

      <Section title="8. Acceptable Use">
        <P>You agree not to:</P>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Use PassAI for any illegal purpose.</li>
          <li>Attempt to access other users' accounts or data.</li>
          <li>Reverse engineer, decompile, or attempt to extract the source code of PassAI.</li>
          <li>Use automated tools (bots, scrapers) to access the Service.</li>
          <li>Resell or redistribute PassAI or its content.</li>
          <li>Interfere with the operation of the Service.</li>
          <li>Use PassAI to generate content for purposes other than personal study.</li>
        </ul>
      </Section>

      <Section title="9. Intellectual Property">
        <P>PassAI, including its design, code, garden metaphor, visual assets, and branding, is owned by Shryn, Inc. These Terms do not grant you any rights to our intellectual property except the right to use the Service as described here.</P>
      </Section>

      <Section title="10. Disclaimers">
        <P>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." WE MAKE NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</P>
        <P>WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE. WE DO NOT WARRANT THE ACCURACY OF AI-GENERATED CONTENT.</P>
      </Section>

      <Section title="11. Limitation of Liability">
        <P>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHRYN, INC. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO EXAM RESULTS, LOST DATA, OR INTERRUPTIONS TO YOUR STUDY SCHEDULE.</P>
        <P>OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $79, WHICHEVER IS GREATER.</P>
      </Section>

      <Section title="12. Indemnification">
        <P>You agree to indemnify and hold harmless Shryn, Inc. from any claims, damages, or expenses arising from your use of the Service or your violation of these Terms.</P>
      </Section>

      <Section title="13. Termination">
        <P>You may delete your account at any time. We may suspend or terminate your account if you violate these Terms, with or without notice.</P>
        <P>Upon termination, your right to use the Service ends. We will delete your data within 30 days, except where we are required to retain it by law.</P>
      </Section>

      <Section title="14. Dispute Resolution">
        <P>These Terms are governed by the laws of the State of New Jersey, United States, without regard to conflict of law principles.</P>
        <P>Any disputes arising from these Terms or the Service shall be resolved through binding arbitration under the rules of the American Arbitration Association, except that either party may seek injunctive relief in court. Class actions and class arbitrations are not permitted.</P>
        <P>If you are located in the EU, this section does not limit your right to bring a claim in your local courts.</P>
      </Section>

      <Section title="15. Changes to These Terms">
        <P>We may update these Terms. If we make material changes, we will notify you by email or by a notice within the app at least 30 days before the changes take effect. Continued use of the Service after changes take effect constitutes acceptance.</P>
      </Section>

      <Section title="16. Severability">
        <P>If any provision of these Terms is found to be unenforceable, the remaining provisions continue in full force.</P>
      </Section>

      <Section title="17. Contact">
        <P>Questions about these Terms? Contact us at:</P>
        <P><strong>Shryn, Inc.</strong><br />Email: <a href="mailto:passai.study@gmail.com" className="text-primary hover:underline">passai.study@gmail.com</a></P>
      </Section>
    </LegalPageLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border/40">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="text-base font-semibold text-foreground mt-5 mb-2">{children}</h3>;
}

function P({ children, className }: { children: React.ReactNode; className?: string }) {
  return <p className={`text-sm text-muted-foreground leading-relaxed ${className ?? ""}`}>{children}</p>;
}
